name: Render and Deploy Quarto Cookbook

on:
  # This allows it to be triggered for testing. Should delete in final version?
  
  workflow_dispatch:
  push:
    branches: [main, dev, fr/testing-cookbook-deploy-action]

jobs:
  render-cookbook:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
        # with:
        #   enablement: true

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # - name: Install Pandoc (if needed)
      #   run: sudo apt-get install -y pandoc

      - name: Render Quarto project
        run: quarto render ./src/afcharts/cookbook

  deploy:
    needs: render-cookbook

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    runs-on: ubuntu-latest

    steps:
      # Upload the book's HTML as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src/afcharts/cookbook/docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/afcharts/cookbook/docs
